print("=== Baseball Stats ===")
name = input("Name: ")
position = input("Position: ")
at_bats = int(input("At-Bats (AB): "))
hits = int(input("Hits (H): "))
walks = int(input("Walks (W): "))
doubles = int(input("Doubles (2B): "))
triples = int(input("Triples (3B): "))
home_runs = int(input("Home Runs (HR): "))
sac_fly = int(input("Sacrifice Flies (SF): "))

total_bases = (2 * doubles) + (3 * triples) + (4 * home_runs)

avg = (float)(hits / at_bats)
obp = (float)((hits + walks) / (at_bats + walks + sac_fly))
slg = (float)(total_bases / at_bats)
ops = (float)(obp + slg)

print(f"Player: {name}")
print(f"{name}'s position: {position}")
print(f"AVG: {avg:.3f}")
print(f"OBP: {obp:.3f}")
print(f"SLG: {slg:.3f}")
print(f"OPS: {ops:.3f}")
print(f"Home runs: {home_runs}")